# Generated by Django 5.2.17 on 2026-08-15 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("audit_created_at", models.DateTimeField(auto_now_add=True)),
                ("audit_modified_at", models.DateTimeField(auto_now=True)),
                ("devEUI", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("passing", "Passing"), ("failing", "Failing")],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("audit_created_at", models.DateTimeField(auto_now_add=True)),
                ("audit_modified_at", models.DateTimeField(auto_now=True)),
                ("fCnt", models.IntegerField()),
                ("data", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("passing", "Passing"), ("failing", "Failing")], max_length=16
                    ),
                ),
                ("raw_payload", models.JSONField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payloads",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("device", "fCnt"), name="unique_device_fcnt")
                ],
            },
        ),
    ]
