# Generated by Django 5.2.17 on 2026-08-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="payload",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
